// Code generated by entc, DO NOT EDIT.

package settings

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the settings type in the database.
	Label = "settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSuccessWebhook holds the string denoting the successwebhook field in the database.
	FieldSuccessWebhook = "success_webhook"
	// FieldDeclineWebhook holds the string denoting the declinewebhook field in the database.
	FieldDeclineWebhook = "decline_webhook"
	// FieldCheckoutDelay holds the string denoting the checkoutdelay field in the database.
	FieldCheckoutDelay = "checkout_delay"
	// FieldATCDelay holds the string denoting the atcdelay field in the database.
	FieldATCDelay = "atc_delay"
	// FieldCaptchaSolver holds the string denoting the captchasolver field in the database.
	FieldCaptchaSolver = "captcha_solver"
	// FieldCaptchaDetails holds the string denoting the captchadetails field in the database.
	FieldCaptchaDetails = "captcha_details"
	// EdgeApp holds the string denoting the app edge name in mutations.
	EdgeApp = "App"
	// Table holds the table name of the settings in the database.
	Table = "settings"
	// AppTable is the table that holds the App relation/edge.
	AppTable = "settings"
	// AppInverseTable is the table name for the App entity.
	// It exists in this package in order to avoid circular dependency with the "app" package.
	AppInverseTable = "apps"
	// AppColumn is the table column denoting the App relation/edge.
	AppColumn = "app_settings"
)

// Columns holds all SQL columns for settings fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSuccessWebhook,
	FieldDeclineWebhook,
	FieldCheckoutDelay,
	FieldATCDelay,
	FieldCaptchaSolver,
	FieldCaptchaDetails,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "settings"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"app_settings",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultSuccessWebhook holds the default value on creation for the "SuccessWebhook" field.
	DefaultSuccessWebhook string
	// DefaultDeclineWebhook holds the default value on creation for the "DeclineWebhook" field.
	DefaultDeclineWebhook string
	// DefaultCheckoutDelay holds the default value on creation for the "CheckoutDelay" field.
	DefaultCheckoutDelay int32
	// DefaultATCDelay holds the default value on creation for the "ATCDelay" field.
	DefaultATCDelay int32
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// CaptchaSolver defines the type for the "CaptchaSolver" enum field.
type CaptchaSolver string

// CaptchaSolverDisabled is the default value of the CaptchaSolver enum.
const DefaultCaptchaSolver = CaptchaSolverDisabled

// CaptchaSolver values.
const (
	CaptchaSolverAYCD_Autosolve CaptchaSolver = "AYCD_Autosolve"
	CaptchaSolver2Captcha       CaptchaSolver = "2Captcha"
	CaptchaSolverCapMonster     CaptchaSolver = "CapMonster"
	CaptchaSolverHarvester      CaptchaSolver = "Harvester"
	CaptchaSolverDisabled       CaptchaSolver = "Disabled"
)

func (_captchasolver CaptchaSolver) String() string {
	return string(_captchasolver)
}

// CaptchaSolverValidator is a validator for the "CaptchaSolver" field enum values. It is called by the builders before save.
func CaptchaSolverValidator(_captchasolver CaptchaSolver) error {
	switch _captchasolver {
	case CaptchaSolverAYCD_Autosolve, CaptchaSolver2Captcha, CaptchaSolverCapMonster, CaptchaSolverHarvester, CaptchaSolverDisabled:
		return nil
	default:
		return fmt.Errorf("settings: invalid enum value for CaptchaSolver field: %q", _captchasolver)
	}
}

// MarshalGQL implements graphql.Marshaler interface.
func (_captchasolver CaptchaSolver) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(_captchasolver.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (_captchasolver *CaptchaSolver) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*_captchasolver = CaptchaSolver(str)
	if err := CaptchaSolverValidator(*_captchasolver); err != nil {
		return fmt.Errorf("%s is not a valid CaptchaSolver", str)
	}
	return nil
}
