// Code generated by entc, DO NOT EDIT.

package proxy

const (
	// Label holds the string label denoting the proxy type in the database.
	Label = "proxy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// EdgeProxyList holds the string denoting the proxylist edge name in mutations.
	EdgeProxyList = "ProxyList"
	// Table holds the table name of the proxy in the database.
	Table = "proxies"
	// ProxyListTable is the table the holds the ProxyList relation/edge.
	ProxyListTable = "proxies"
	// ProxyListInverseTable is the table name for the ProxyList entity.
	// It exists in this package in order to avoid circular dependency with the "proxylist" package.
	ProxyListInverseTable = "proxy_lists"
	// ProxyListColumn is the table column denoting the ProxyList relation/edge.
	ProxyListColumn = "proxy_list_proxies"
)

// Columns holds all SQL columns for proxy fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldPassword,
	FieldIP,
	FieldPort,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "proxies"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"proxy_list_proxies",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
