// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ProjectAthenaa/sonic-core/sonic/database/ent/accountgroup"
	"github.com/ProjectAthenaa/sonic-core/sonic/database/ent/app"
	"github.com/ProjectAthenaa/sonic-core/sonic/database/ent/predicate"
)

// AccountGroupQuery is the builder for querying AccountGroup entities.
type AccountGroupQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AccountGroup
	// eager-loading edges.
	withApp *AppQuery
	withFKs bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AccountGroupQuery builder.
func (agq *AccountGroupQuery) Where(ps ...predicate.AccountGroup) *AccountGroupQuery {
	agq.predicates = append(agq.predicates, ps...)
	return agq
}

// Limit adds a limit step to the query.
func (agq *AccountGroupQuery) Limit(limit int) *AccountGroupQuery {
	agq.limit = &limit
	return agq
}

// Offset adds an offset step to the query.
func (agq *AccountGroupQuery) Offset(offset int) *AccountGroupQuery {
	agq.offset = &offset
	return agq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (agq *AccountGroupQuery) Unique(unique bool) *AccountGroupQuery {
	agq.unique = &unique
	return agq
}

// Order adds an order step to the query.
func (agq *AccountGroupQuery) Order(o ...OrderFunc) *AccountGroupQuery {
	agq.order = append(agq.order, o...)
	return agq
}

// QueryApp chains the current query on the "App" edge.
func (agq *AccountGroupQuery) QueryApp() *AppQuery {
	query := &AppQuery{config: agq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := agq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := agq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accountgroup.Table, accountgroup.FieldID, selector),
			sqlgraph.To(app.Table, app.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, accountgroup.AppTable, accountgroup.AppColumn),
		)
		fromU = sqlgraph.SetNeighbors(agq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AccountGroup entity from the query.
// Returns a *NotFoundError when no AccountGroup was found.
func (agq *AccountGroupQuery) First(ctx context.Context) (*AccountGroup, error) {
	nodes, err := agq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{accountgroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (agq *AccountGroupQuery) FirstX(ctx context.Context) *AccountGroup {
	node, err := agq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AccountGroup ID from the query.
// Returns a *NotFoundError when no AccountGroup ID was found.
func (agq *AccountGroupQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = agq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{accountgroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (agq *AccountGroupQuery) FirstIDX(ctx context.Context) int {
	id, err := agq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AccountGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one AccountGroup entity is not found.
// Returns a *NotFoundError when no AccountGroup entities are found.
func (agq *AccountGroupQuery) Only(ctx context.Context) (*AccountGroup, error) {
	nodes, err := agq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{accountgroup.Label}
	default:
		return nil, &NotSingularError{accountgroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (agq *AccountGroupQuery) OnlyX(ctx context.Context) *AccountGroup {
	node, err := agq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AccountGroup ID in the query.
// Returns a *NotSingularError when exactly one AccountGroup ID is not found.
// Returns a *NotFoundError when no entities are found.
func (agq *AccountGroupQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = agq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{accountgroup.Label}
	default:
		err = &NotSingularError{accountgroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (agq *AccountGroupQuery) OnlyIDX(ctx context.Context) int {
	id, err := agq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AccountGroups.
func (agq *AccountGroupQuery) All(ctx context.Context) ([]*AccountGroup, error) {
	if err := agq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return agq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (agq *AccountGroupQuery) AllX(ctx context.Context) []*AccountGroup {
	nodes, err := agq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AccountGroup IDs.
func (agq *AccountGroupQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := agq.Select(accountgroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (agq *AccountGroupQuery) IDsX(ctx context.Context) []int {
	ids, err := agq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (agq *AccountGroupQuery) Count(ctx context.Context) (int, error) {
	if err := agq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return agq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (agq *AccountGroupQuery) CountX(ctx context.Context) int {
	count, err := agq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (agq *AccountGroupQuery) Exist(ctx context.Context) (bool, error) {
	if err := agq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return agq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (agq *AccountGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := agq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AccountGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (agq *AccountGroupQuery) Clone() *AccountGroupQuery {
	if agq == nil {
		return nil
	}
	return &AccountGroupQuery{
		config:     agq.config,
		limit:      agq.limit,
		offset:     agq.offset,
		order:      append([]OrderFunc{}, agq.order...),
		predicates: append([]predicate.AccountGroup{}, agq.predicates...),
		withApp:    agq.withApp.Clone(),
		// clone intermediate query.
		sql:  agq.sql.Clone(),
		path: agq.path,
	}
}

// WithApp tells the query-builder to eager-load the nodes that are connected to
// the "App" edge. The optional arguments are used to configure the query builder of the edge.
func (agq *AccountGroupQuery) WithApp(opts ...func(*AppQuery)) *AccountGroupQuery {
	query := &AppQuery{config: agq.config}
	for _, opt := range opts {
		opt(query)
	}
	agq.withApp = query
	return agq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AccountGroup.Query().
//		GroupBy(accountgroup.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (agq *AccountGroupQuery) GroupBy(field string, fields ...string) *AccountGroupGroupBy {
	group := &AccountGroupGroupBy{config: agq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := agq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return agq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//	}
//
//	client.AccountGroup.Query().
//		Select(accountgroup.FieldName).
//		Scan(ctx, &v)
//
func (agq *AccountGroupQuery) Select(field string, fields ...string) *AccountGroupSelect {
	agq.fields = append([]string{field}, fields...)
	return &AccountGroupSelect{AccountGroupQuery: agq}
}

func (agq *AccountGroupQuery) prepareQuery(ctx context.Context) error {
	for _, f := range agq.fields {
		if !accountgroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if agq.path != nil {
		prev, err := agq.path(ctx)
		if err != nil {
			return err
		}
		agq.sql = prev
	}
	return nil
}

func (agq *AccountGroupQuery) sqlAll(ctx context.Context) ([]*AccountGroup, error) {
	var (
		nodes       = []*AccountGroup{}
		withFKs     = agq.withFKs
		_spec       = agq.querySpec()
		loadedTypes = [1]bool{
			agq.withApp != nil,
		}
	)
	if agq.withApp != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, accountgroup.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AccountGroup{config: agq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, agq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := agq.withApp; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*AccountGroup)
		for i := range nodes {
			if nodes[i].app_account_groups == nil {
				continue
			}
			fk := *nodes[i].app_account_groups
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(app.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "app_account_groups" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.App = n
			}
		}
	}

	return nodes, nil
}

func (agq *AccountGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := agq.querySpec()
	return sqlgraph.CountNodes(ctx, agq.driver, _spec)
}

func (agq *AccountGroupQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := agq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (agq *AccountGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   accountgroup.Table,
			Columns: accountgroup.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: accountgroup.FieldID,
			},
		},
		From:   agq.sql,
		Unique: true,
	}
	if unique := agq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := agq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountgroup.FieldID)
		for i := range fields {
			if fields[i] != accountgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := agq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := agq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := agq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := agq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (agq *AccountGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(agq.driver.Dialect())
	t1 := builder.Table(accountgroup.Table)
	selector := builder.Select(t1.Columns(accountgroup.Columns...)...).From(t1)
	if agq.sql != nil {
		selector = agq.sql
		selector.Select(selector.Columns(accountgroup.Columns...)...)
	}
	for _, p := range agq.predicates {
		p(selector)
	}
	for _, p := range agq.order {
		p(selector)
	}
	if offset := agq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := agq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AccountGroupGroupBy is the group-by builder for AccountGroup entities.
type AccountGroupGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aggb *AccountGroupGroupBy) Aggregate(fns ...AggregateFunc) *AccountGroupGroupBy {
	aggb.fns = append(aggb.fns, fns...)
	return aggb
}

// Scan applies the group-by query and scans the result into the given value.
func (aggb *AccountGroupGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := aggb.path(ctx)
	if err != nil {
		return err
	}
	aggb.sql = query
	return aggb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (aggb *AccountGroupGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := aggb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (aggb *AccountGroupGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(aggb.fields) > 1 {
		return nil, errors.New("ent: AccountGroupGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := aggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (aggb *AccountGroupGroupBy) StringsX(ctx context.Context) []string {
	v, err := aggb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aggb *AccountGroupGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = aggb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accountgroup.Label}
	default:
		err = fmt.Errorf("ent: AccountGroupGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (aggb *AccountGroupGroupBy) StringX(ctx context.Context) string {
	v, err := aggb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (aggb *AccountGroupGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(aggb.fields) > 1 {
		return nil, errors.New("ent: AccountGroupGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := aggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (aggb *AccountGroupGroupBy) IntsX(ctx context.Context) []int {
	v, err := aggb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aggb *AccountGroupGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = aggb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accountgroup.Label}
	default:
		err = fmt.Errorf("ent: AccountGroupGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (aggb *AccountGroupGroupBy) IntX(ctx context.Context) int {
	v, err := aggb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (aggb *AccountGroupGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(aggb.fields) > 1 {
		return nil, errors.New("ent: AccountGroupGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := aggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (aggb *AccountGroupGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := aggb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aggb *AccountGroupGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = aggb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accountgroup.Label}
	default:
		err = fmt.Errorf("ent: AccountGroupGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (aggb *AccountGroupGroupBy) Float64X(ctx context.Context) float64 {
	v, err := aggb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (aggb *AccountGroupGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(aggb.fields) > 1 {
		return nil, errors.New("ent: AccountGroupGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := aggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (aggb *AccountGroupGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := aggb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aggb *AccountGroupGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = aggb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accountgroup.Label}
	default:
		err = fmt.Errorf("ent: AccountGroupGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (aggb *AccountGroupGroupBy) BoolX(ctx context.Context) bool {
	v, err := aggb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (aggb *AccountGroupGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range aggb.fields {
		if !accountgroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := aggb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aggb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (aggb *AccountGroupGroupBy) sqlQuery() *sql.Selector {
	selector := aggb.sql
	columns := make([]string, 0, len(aggb.fields)+len(aggb.fns))
	columns = append(columns, aggb.fields...)
	for _, fn := range aggb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(aggb.fields...)
}

// AccountGroupSelect is the builder for selecting fields of AccountGroup entities.
type AccountGroupSelect struct {
	*AccountGroupQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ags *AccountGroupSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ags.prepareQuery(ctx); err != nil {
		return err
	}
	ags.sql = ags.AccountGroupQuery.sqlQuery(ctx)
	return ags.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ags *AccountGroupSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ags.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ags *AccountGroupSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ags.fields) > 1 {
		return nil, errors.New("ent: AccountGroupSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ags.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ags *AccountGroupSelect) StringsX(ctx context.Context) []string {
	v, err := ags.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ags *AccountGroupSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ags.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accountgroup.Label}
	default:
		err = fmt.Errorf("ent: AccountGroupSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ags *AccountGroupSelect) StringX(ctx context.Context) string {
	v, err := ags.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ags *AccountGroupSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ags.fields) > 1 {
		return nil, errors.New("ent: AccountGroupSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ags.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ags *AccountGroupSelect) IntsX(ctx context.Context) []int {
	v, err := ags.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ags *AccountGroupSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ags.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accountgroup.Label}
	default:
		err = fmt.Errorf("ent: AccountGroupSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ags *AccountGroupSelect) IntX(ctx context.Context) int {
	v, err := ags.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ags *AccountGroupSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ags.fields) > 1 {
		return nil, errors.New("ent: AccountGroupSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ags.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ags *AccountGroupSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ags.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ags *AccountGroupSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ags.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accountgroup.Label}
	default:
		err = fmt.Errorf("ent: AccountGroupSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ags *AccountGroupSelect) Float64X(ctx context.Context) float64 {
	v, err := ags.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ags *AccountGroupSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ags.fields) > 1 {
		return nil, errors.New("ent: AccountGroupSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ags.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ags *AccountGroupSelect) BoolsX(ctx context.Context) []bool {
	v, err := ags.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ags *AccountGroupSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ags.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accountgroup.Label}
	default:
		err = fmt.Errorf("ent: AccountGroupSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ags *AccountGroupSelect) BoolX(ctx context.Context) bool {
	v, err := ags.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ags *AccountGroupSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ags.sqlQuery().Query()
	if err := ags.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ags *AccountGroupSelect) sqlQuery() sql.Querier {
	selector := ags.sql
	selector.Select(selector.Columns(ags.fields...)...)
	return selector
}
