// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ProjectAthenaa/sonic-core/sonic/database/ent/app"
	"github.com/ProjectAthenaa/sonic-core/sonic/database/ent/predicate"
	"github.com/ProjectAthenaa/sonic-core/sonic/database/ent/profile"
	"github.com/ProjectAthenaa/sonic-core/sonic/database/ent/profilegroup"
	"github.com/ProjectAthenaa/sonic-core/sonic/database/ent/task"
	"github.com/google/uuid"
)

// ProfileGroupQuery is the builder for querying ProfileGroup entities.
type ProfileGroupQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ProfileGroup
	// eager-loading edges.
	withProfiles     *ProfileQuery
	withApp          *AppQuery
	withProfileGroup *TaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProfileGroupQuery builder.
func (pgq *ProfileGroupQuery) Where(ps ...predicate.ProfileGroup) *ProfileGroupQuery {
	pgq.predicates = append(pgq.predicates, ps...)
	return pgq
}

// Limit adds a limit step to the query.
func (pgq *ProfileGroupQuery) Limit(limit int) *ProfileGroupQuery {
	pgq.limit = &limit
	return pgq
}

// Offset adds an offset step to the query.
func (pgq *ProfileGroupQuery) Offset(offset int) *ProfileGroupQuery {
	pgq.offset = &offset
	return pgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pgq *ProfileGroupQuery) Unique(unique bool) *ProfileGroupQuery {
	pgq.unique = &unique
	return pgq
}

// Order adds an order step to the query.
func (pgq *ProfileGroupQuery) Order(o ...OrderFunc) *ProfileGroupQuery {
	pgq.order = append(pgq.order, o...)
	return pgq
}

// QueryProfiles chains the current query on the "Profiles" edge.
func (pgq *ProfileGroupQuery) QueryProfiles() *ProfileQuery {
	query := &ProfileQuery{config: pgq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(profilegroup.Table, profilegroup.FieldID, selector),
			sqlgraph.To(profile.Table, profile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, profilegroup.ProfilesTable, profilegroup.ProfilesColumn),
		)
		fromU = sqlgraph.SetNeighbors(pgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryApp chains the current query on the "App" edge.
func (pgq *ProfileGroupQuery) QueryApp() *AppQuery {
	query := &AppQuery{config: pgq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(profilegroup.Table, profilegroup.FieldID, selector),
			sqlgraph.To(app.Table, app.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, profilegroup.AppTable, profilegroup.AppPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(pgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProfileGroup chains the current query on the "ProfileGroup" edge.
func (pgq *ProfileGroupQuery) QueryProfileGroup() *TaskQuery {
	query := &TaskQuery{config: pgq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(profilegroup.Table, profilegroup.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, profilegroup.ProfileGroupTable, profilegroup.ProfileGroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(pgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProfileGroup entity from the query.
// Returns a *NotFoundError when no ProfileGroup was found.
func (pgq *ProfileGroupQuery) First(ctx context.Context) (*ProfileGroup, error) {
	nodes, err := pgq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{profilegroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pgq *ProfileGroupQuery) FirstX(ctx context.Context) *ProfileGroup {
	node, err := pgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProfileGroup ID from the query.
// Returns a *NotFoundError when no ProfileGroup ID was found.
func (pgq *ProfileGroupQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pgq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{profilegroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pgq *ProfileGroupQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := pgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProfileGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one ProfileGroup entity is not found.
// Returns a *NotFoundError when no ProfileGroup entities are found.
func (pgq *ProfileGroupQuery) Only(ctx context.Context) (*ProfileGroup, error) {
	nodes, err := pgq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{profilegroup.Label}
	default:
		return nil, &NotSingularError{profilegroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pgq *ProfileGroupQuery) OnlyX(ctx context.Context) *ProfileGroup {
	node, err := pgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProfileGroup ID in the query.
// Returns a *NotSingularError when exactly one ProfileGroup ID is not found.
// Returns a *NotFoundError when no entities are found.
func (pgq *ProfileGroupQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pgq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{profilegroup.Label}
	default:
		err = &NotSingularError{profilegroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pgq *ProfileGroupQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := pgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProfileGroups.
func (pgq *ProfileGroupQuery) All(ctx context.Context) ([]*ProfileGroup, error) {
	if err := pgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pgq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pgq *ProfileGroupQuery) AllX(ctx context.Context) []*ProfileGroup {
	nodes, err := pgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProfileGroup IDs.
func (pgq *ProfileGroupQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := pgq.Select(profilegroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pgq *ProfileGroupQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := pgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pgq *ProfileGroupQuery) Count(ctx context.Context) (int, error) {
	if err := pgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pgq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pgq *ProfileGroupQuery) CountX(ctx context.Context) int {
	count, err := pgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pgq *ProfileGroupQuery) Exist(ctx context.Context) (bool, error) {
	if err := pgq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pgq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pgq *ProfileGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := pgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProfileGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pgq *ProfileGroupQuery) Clone() *ProfileGroupQuery {
	if pgq == nil {
		return nil
	}
	return &ProfileGroupQuery{
		config:           pgq.config,
		limit:            pgq.limit,
		offset:           pgq.offset,
		order:            append([]OrderFunc{}, pgq.order...),
		predicates:       append([]predicate.ProfileGroup{}, pgq.predicates...),
		withProfiles:     pgq.withProfiles.Clone(),
		withApp:          pgq.withApp.Clone(),
		withProfileGroup: pgq.withProfileGroup.Clone(),
		// clone intermediate query.
		sql:  pgq.sql.Clone(),
		path: pgq.path,
	}
}

// WithProfiles tells the query-builder to eager-load the nodes that are connected to
// the "Profiles" edge. The optional arguments are used to configure the query builder of the edge.
func (pgq *ProfileGroupQuery) WithProfiles(opts ...func(*ProfileQuery)) *ProfileGroupQuery {
	query := &ProfileQuery{config: pgq.config}
	for _, opt := range opts {
		opt(query)
	}
	pgq.withProfiles = query
	return pgq
}

// WithApp tells the query-builder to eager-load the nodes that are connected to
// the "App" edge. The optional arguments are used to configure the query builder of the edge.
func (pgq *ProfileGroupQuery) WithApp(opts ...func(*AppQuery)) *ProfileGroupQuery {
	query := &AppQuery{config: pgq.config}
	for _, opt := range opts {
		opt(query)
	}
	pgq.withApp = query
	return pgq
}

// WithProfileGroup tells the query-builder to eager-load the nodes that are connected to
// the "ProfileGroup" edge. The optional arguments are used to configure the query builder of the edge.
func (pgq *ProfileGroupQuery) WithProfileGroup(opts ...func(*TaskQuery)) *ProfileGroupQuery {
	query := &TaskQuery{config: pgq.config}
	for _, opt := range opts {
		opt(query)
	}
	pgq.withProfileGroup = query
	return pgq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProfileGroup.Query().
//		GroupBy(profilegroup.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (pgq *ProfileGroupQuery) GroupBy(field string, fields ...string) *ProfileGroupGroupBy {
	group := &ProfileGroupGroupBy{config: pgq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pgq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ProfileGroup.Query().
//		Select(profilegroup.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (pgq *ProfileGroupQuery) Select(fields ...string) *ProfileGroupSelect {
	pgq.fields = append(pgq.fields, fields...)
	return &ProfileGroupSelect{ProfileGroupQuery: pgq}
}

func (pgq *ProfileGroupQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pgq.fields {
		if !profilegroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pgq.path != nil {
		prev, err := pgq.path(ctx)
		if err != nil {
			return err
		}
		pgq.sql = prev
	}
	return nil
}

func (pgq *ProfileGroupQuery) sqlAll(ctx context.Context) ([]*ProfileGroup, error) {
	var (
		nodes       = []*ProfileGroup{}
		_spec       = pgq.querySpec()
		loadedTypes = [3]bool{
			pgq.withProfiles != nil,
			pgq.withApp != nil,
			pgq.withProfileGroup != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ProfileGroup{config: pgq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, pgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := pgq.withProfiles; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[uuid.UUID]*ProfileGroup)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Profiles = []*Profile{}
		}
		query.withFKs = true
		query.Where(predicate.Profile(func(s *sql.Selector) {
			s.Where(sql.InValues(profilegroup.ProfilesColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.profile_group_profiles
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "profile_group_profiles" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "profile_group_profiles" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Profiles = append(node.Edges.Profiles, n)
		}
	}

	if query := pgq.withApp; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[uuid.UUID]*ProfileGroup, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
			node.Edges.App = []*App{}
		}
		var (
			edgeids []uuid.UUID
			edges   = make(map[uuid.UUID][]*ProfileGroup)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: true,
				Table:   profilegroup.AppTable,
				Columns: profilegroup.AppPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(profilegroup.AppPrimaryKey[1], fks...))
			},
			ScanValues: func() [2]interface{} {
				return [2]interface{}{new(uuid.UUID), new(uuid.UUID)}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*uuid.UUID)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*uuid.UUID)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := *eout
				inValue := *ein
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				if _, ok := edges[inValue]; !ok {
					edgeids = append(edgeids, inValue)
				}
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, pgq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "App": %w`, err)
		}
		query.Where(app.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "App" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.App = append(nodes[i].Edges.App, n)
			}
		}
	}

	if query := pgq.withProfileGroup; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[uuid.UUID]*ProfileGroup)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.ProfileGroup = []*Task{}
		}
		query.withFKs = true
		query.Where(predicate.Task(func(s *sql.Selector) {
			s.Where(sql.InValues(profilegroup.ProfileGroupColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.profile_group_profile_group
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "profile_group_profile_group" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "profile_group_profile_group" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.ProfileGroup = append(node.Edges.ProfileGroup, n)
		}
	}

	return nodes, nil
}

func (pgq *ProfileGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pgq.querySpec()
	return sqlgraph.CountNodes(ctx, pgq.driver, _spec)
}

func (pgq *ProfileGroupQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := pgq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (pgq *ProfileGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   profilegroup.Table,
			Columns: profilegroup.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: profilegroup.FieldID,
			},
		},
		From:   pgq.sql,
		Unique: true,
	}
	if unique := pgq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pgq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profilegroup.FieldID)
		for i := range fields {
			if fields[i] != profilegroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pgq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pgq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pgq *ProfileGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pgq.driver.Dialect())
	t1 := builder.Table(profilegroup.Table)
	columns := pgq.fields
	if len(columns) == 0 {
		columns = profilegroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pgq.sql != nil {
		selector = pgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range pgq.predicates {
		p(selector)
	}
	for _, p := range pgq.order {
		p(selector)
	}
	if offset := pgq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pgq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProfileGroupGroupBy is the group-by builder for ProfileGroup entities.
type ProfileGroupGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pggb *ProfileGroupGroupBy) Aggregate(fns ...AggregateFunc) *ProfileGroupGroupBy {
	pggb.fns = append(pggb.fns, fns...)
	return pggb
}

// Scan applies the group-by query and scans the result into the given value.
func (pggb *ProfileGroupGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pggb.path(ctx)
	if err != nil {
		return err
	}
	pggb.sql = query
	return pggb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pggb *ProfileGroupGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pggb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfileGroupGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pggb.fields) > 1 {
		return nil, errors.New("ent: ProfileGroupGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pggb *ProfileGroupGroupBy) StringsX(ctx context.Context) []string {
	v, err := pggb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfileGroupGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pggb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profilegroup.Label}
	default:
		err = fmt.Errorf("ent: ProfileGroupGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pggb *ProfileGroupGroupBy) StringX(ctx context.Context) string {
	v, err := pggb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfileGroupGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pggb.fields) > 1 {
		return nil, errors.New("ent: ProfileGroupGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pggb *ProfileGroupGroupBy) IntsX(ctx context.Context) []int {
	v, err := pggb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfileGroupGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pggb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profilegroup.Label}
	default:
		err = fmt.Errorf("ent: ProfileGroupGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pggb *ProfileGroupGroupBy) IntX(ctx context.Context) int {
	v, err := pggb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfileGroupGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pggb.fields) > 1 {
		return nil, errors.New("ent: ProfileGroupGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pggb *ProfileGroupGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pggb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfileGroupGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pggb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profilegroup.Label}
	default:
		err = fmt.Errorf("ent: ProfileGroupGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pggb *ProfileGroupGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pggb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfileGroupGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pggb.fields) > 1 {
		return nil, errors.New("ent: ProfileGroupGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pggb *ProfileGroupGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pggb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfileGroupGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pggb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profilegroup.Label}
	default:
		err = fmt.Errorf("ent: ProfileGroupGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pggb *ProfileGroupGroupBy) BoolX(ctx context.Context) bool {
	v, err := pggb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pggb *ProfileGroupGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pggb.fields {
		if !profilegroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pggb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pggb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pggb *ProfileGroupGroupBy) sqlQuery() *sql.Selector {
	selector := pggb.sql.Select()
	aggregation := make([]string, 0, len(pggb.fns))
	for _, fn := range pggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pggb.fields)+len(pggb.fns))
		for _, f := range pggb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pggb.fields...)...)
}

// ProfileGroupSelect is the builder for selecting fields of ProfileGroup entities.
type ProfileGroupSelect struct {
	*ProfileGroupQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pgs *ProfileGroupSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pgs.prepareQuery(ctx); err != nil {
		return err
	}
	pgs.sql = pgs.ProfileGroupQuery.sqlQuery(ctx)
	return pgs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pgs *ProfileGroupSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pgs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (pgs *ProfileGroupSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pgs.fields) > 1 {
		return nil, errors.New("ent: ProfileGroupSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pgs *ProfileGroupSelect) StringsX(ctx context.Context) []string {
	v, err := pgs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (pgs *ProfileGroupSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pgs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profilegroup.Label}
	default:
		err = fmt.Errorf("ent: ProfileGroupSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pgs *ProfileGroupSelect) StringX(ctx context.Context) string {
	v, err := pgs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (pgs *ProfileGroupSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pgs.fields) > 1 {
		return nil, errors.New("ent: ProfileGroupSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pgs *ProfileGroupSelect) IntsX(ctx context.Context) []int {
	v, err := pgs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (pgs *ProfileGroupSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pgs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profilegroup.Label}
	default:
		err = fmt.Errorf("ent: ProfileGroupSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pgs *ProfileGroupSelect) IntX(ctx context.Context) int {
	v, err := pgs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (pgs *ProfileGroupSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pgs.fields) > 1 {
		return nil, errors.New("ent: ProfileGroupSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pgs *ProfileGroupSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pgs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (pgs *ProfileGroupSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pgs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profilegroup.Label}
	default:
		err = fmt.Errorf("ent: ProfileGroupSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pgs *ProfileGroupSelect) Float64X(ctx context.Context) float64 {
	v, err := pgs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (pgs *ProfileGroupSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pgs.fields) > 1 {
		return nil, errors.New("ent: ProfileGroupSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pgs *ProfileGroupSelect) BoolsX(ctx context.Context) []bool {
	v, err := pgs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (pgs *ProfileGroupSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pgs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profilegroup.Label}
	default:
		err = fmt.Errorf("ent: ProfileGroupSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pgs *ProfileGroupSelect) BoolX(ctx context.Context) bool {
	v, err := pgs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pgs *ProfileGroupSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pgs.sql.Query()
	if err := pgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
