// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package perimeterx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PerimeterXClient is the client API for PerimeterX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PerimeterXClient interface {
	PX2(ctx context.Context, in *PX2Request, opts ...grpc.CallOption) (*Payload, error)
	PX3(ctx context.Context, in *PXRequest, opts ...grpc.CallOption) (*Payload, error)
	GetCookie(ctx context.Context, in *CookieRequest, opts ...grpc.CallOption) (*Cookies, error)
}

type perimeterXClient struct {
	cc grpc.ClientConnInterface
}

func NewPerimeterXClient(cc grpc.ClientConnInterface) PerimeterXClient {
	return &perimeterXClient{cc}
}

func (c *perimeterXClient) PX2(ctx context.Context, in *PX2Request, opts ...grpc.CallOption) (*Payload, error) {
	out := new(Payload)
	err := c.cc.Invoke(ctx, "/perimeterx.PerimeterX/PX2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *perimeterXClient) PX3(ctx context.Context, in *PXRequest, opts ...grpc.CallOption) (*Payload, error) {
	out := new(Payload)
	err := c.cc.Invoke(ctx, "/perimeterx.PerimeterX/PX3", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *perimeterXClient) GetCookie(ctx context.Context, in *CookieRequest, opts ...grpc.CallOption) (*Cookies, error) {
	out := new(Cookies)
	err := c.cc.Invoke(ctx, "/perimeterx.PerimeterX/GetCookie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PerimeterXServer is the server API for PerimeterX service.
// All implementations must embed UnimplementedPerimeterXServer
// for forward compatibility
type PerimeterXServer interface {
	PX2(context.Context, *PX2Request) (*Payload, error)
	PX3(context.Context, *PXRequest) (*Payload, error)
	GetCookie(context.Context, *CookieRequest) (*Cookies, error)
	mustEmbedUnimplementedPerimeterXServer()
}

// UnimplementedPerimeterXServer must be embedded to have forward compatible implementations.
type UnimplementedPerimeterXServer struct {
}

func (UnimplementedPerimeterXServer) PX2(context.Context, *PX2Request) (*Payload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PX2 not implemented")
}
func (UnimplementedPerimeterXServer) PX3(context.Context, *PXRequest) (*Payload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PX3 not implemented")
}
func (UnimplementedPerimeterXServer) GetCookie(context.Context, *CookieRequest) (*Cookies, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCookie not implemented")
}
func (UnimplementedPerimeterXServer) mustEmbedUnimplementedPerimeterXServer() {}

// UnsafePerimeterXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PerimeterXServer will
// result in compilation errors.
type UnsafePerimeterXServer interface {
	mustEmbedUnimplementedPerimeterXServer()
}

func RegisterPerimeterXServer(s grpc.ServiceRegistrar, srv PerimeterXServer) {
	s.RegisterService(&PerimeterX_ServiceDesc, srv)
}

func _PerimeterX_PX2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PX2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerimeterXServer).PX2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perimeterx.PerimeterX/PX2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerimeterXServer).PX2(ctx, req.(*PX2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerimeterX_PX3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PXRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerimeterXServer).PX3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perimeterx.PerimeterX/PX3",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerimeterXServer).PX3(ctx, req.(*PXRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerimeterX_GetCookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CookieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerimeterXServer).GetCookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perimeterx.PerimeterX/GetCookie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerimeterXServer).GetCookie(ctx, req.(*CookieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PerimeterX_ServiceDesc is the grpc.ServiceDesc for PerimeterX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PerimeterX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "perimeterx.PerimeterX",
	HandlerType: (*PerimeterXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PX2",
			Handler:    _PerimeterX_PX2_Handler,
		},
		{
			MethodName: "PX3",
			Handler:    _PerimeterX_PX3_Handler,
		},
		{
			MethodName: "GetCookie",
			Handler:    _PerimeterX_GetCookie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "PerimeterX.proto",
}
