// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.6
// source: PerimeterX.proto

package perimeterx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SITE int32

const (
	SITE_WALMART SITE = 0
	SITE_HIBBET  SITE = 1
	SITE_SSENSE  SITE = 2
	SITE_SNIPES  SITE = 3
	SITE_ONYGO   SITE = 4
	SITE_SOLEBOX SITE = 5
)

// Enum value maps for SITE.
var (
	SITE_name = map[int32]string{
		0: "WALMART",
		1: "HIBBET",
		2: "SSENSE",
		3: "SNIPES",
		4: "ONYGO",
		5: "SOLEBOX",
	}
	SITE_value = map[string]int32{
		"WALMART": 0,
		"HIBBET":  1,
		"SSENSE":  2,
		"SNIPES":  3,
		"ONYGO":   4,
		"SOLEBOX": 5,
	}
)

func (x SITE) Enum() *SITE {
	p := new(SITE)
	*p = x
	return p
}

func (x SITE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SITE) Descriptor() protoreflect.EnumDescriptor {
	return file_PerimeterX_proto_enumTypes[0].Descriptor()
}

func (SITE) Type() protoreflect.EnumType {
	return &file_PerimeterX_proto_enumTypes[0]
}

func (x SITE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SITE.Descriptor instead.
func (SITE) EnumDescriptor() ([]byte, []int) {
	return file_PerimeterX_proto_rawDescGZIP(), []int{0}
}

type PXType int32

const (
	PXType_PX3      PXType = 0
	PXType_PX4      PXType = 1
	PXType_EVENT    PXType = 2
	PXType_MOE      PXType = 3
	PXType_MME      PXType = 4
	PXType_RE       PXType = 5
	PXType_UAE      PXType = 6
	PXType_BRE      PXType = 7
	PXType_HCAPLOW  PXType = 8
	PXType_HCAPHIGH PXType = 9
	PXType_RECAP    PXType = 10
	PXType_PX34     PXType = 11
)

// Enum value maps for PXType.
var (
	PXType_name = map[int32]string{
		0:  "PX3",
		1:  "PX4",
		2:  "EVENT",
		3:  "MOE",
		4:  "MME",
		5:  "RE",
		6:  "UAE",
		7:  "BRE",
		8:  "HCAPLOW",
		9:  "HCAPHIGH",
		10: "RECAP",
		11: "PX34",
	}
	PXType_value = map[string]int32{
		"PX3":      0,
		"PX4":      1,
		"EVENT":    2,
		"MOE":      3,
		"MME":      4,
		"RE":       5,
		"UAE":      6,
		"BRE":      7,
		"HCAPLOW":  8,
		"HCAPHIGH": 9,
		"RECAP":    10,
		"PX34":     11,
	}
)

func (x PXType) Enum() *PXType {
	p := new(PXType)
	*p = x
	return p
}

func (x PXType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PXType) Descriptor() protoreflect.EnumDescriptor {
	return file_PerimeterX_proto_enumTypes[1].Descriptor()
}

func (PXType) Type() protoreflect.EnumType {
	return &file_PerimeterX_proto_enumTypes[1]
}

func (x PXType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PXType.Descriptor instead.
func (PXType) EnumDescriptor() ([]byte, []int) {
	return file_PerimeterX_proto_rawDescGZIP(), []int{1}
}

type GetCookieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PXResponse []byte `protobuf:"bytes,1,opt,name=PXResponse,proto3" json:"PXResponse,omitempty"`
}

func (x *GetCookieRequest) Reset() {
	*x = GetCookieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PerimeterX_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCookieRequest) ProtoMessage() {}

func (x *GetCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PerimeterX_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCookieRequest.ProtoReflect.Descriptor instead.
func (*GetCookieRequest) Descriptor() ([]byte, []int) {
	return file_PerimeterX_proto_rawDescGZIP(), []int{0}
}

func (x *GetCookieRequest) GetPXResponse() []byte {
	if x != nil {
		return x.PXResponse
	}
	return nil
}

type Cookie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Cookie) Reset() {
	*x = Cookie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PerimeterX_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cookie) ProtoMessage() {}

func (x *Cookie) ProtoReflect() protoreflect.Message {
	mi := &file_PerimeterX_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cookie.ProtoReflect.Descriptor instead.
func (*Cookie) Descriptor() ([]byte, []int) {
	return file_PerimeterX_proto_rawDescGZIP(), []int{1}
}

func (x *Cookie) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site           SITE   `protobuf:"varint,1,opt,name=Site,proto3,enum=perimeterx.SITE" json:"Site,omitempty"`
	Type           PXType `protobuf:"varint,2,opt,name=Type,proto3,enum=perimeterx.PXType" json:"Type,omitempty"`
	Cookie         string `protobuf:"bytes,3,opt,name=Cookie,proto3" json:"Cookie,omitempty"`
	ResponseObject []byte `protobuf:"bytes,4,opt,name=ResponseObject,proto3" json:"ResponseObject,omitempty"`
	Token          string `protobuf:"bytes,5,opt,name=Token,proto3" json:"Token,omitempty"`
	RSC            int32  `protobuf:"varint,6,opt,name=RSC,proto3" json:"RSC,omitempty"`
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PerimeterX_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_PerimeterX_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_PerimeterX_proto_rawDescGZIP(), []int{2}
}

func (x *Payload) GetSite() SITE {
	if x != nil {
		return x.Site
	}
	return SITE_WALMART
}

func (x *Payload) GetType() PXType {
	if x != nil {
		return x.Type
	}
	return PXType_PX3
}

func (x *Payload) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

func (x *Payload) GetResponseObject() []byte {
	if x != nil {
		return x.ResponseObject
	}
	return nil
}

func (x *Payload) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Payload) GetRSC() int32 {
	if x != nil {
		return x.RSC
	}
	return 0
}

type ConstructPayloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cookie  string `protobuf:"bytes,1,opt,name=Cookie,proto3" json:"Cookie,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *ConstructPayloadResponse) Reset() {
	*x = ConstructPayloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PerimeterX_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConstructPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstructPayloadResponse) ProtoMessage() {}

func (x *ConstructPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PerimeterX_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstructPayloadResponse.ProtoReflect.Descriptor instead.
func (*ConstructPayloadResponse) Descriptor() ([]byte, []int) {
	return file_PerimeterX_proto_rawDescGZIP(), []int{3}
}

func (x *ConstructPayloadResponse) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

func (x *ConstructPayloadResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_PerimeterX_proto protoreflect.FileDescriptor

var file_PerimeterX_proto_rawDesc = []byte{
	0x0a, 0x10, 0x50, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x58, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x78, 0x22, 0x32,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x58, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x50, 0x58, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x1e, 0x0a, 0x06, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x24,
	0x0a, 0x04, 0x53, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70,
	0x65, 0x72, 0x69, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x78, 0x2e, 0x53, 0x49, 0x54, 0x45, 0x52, 0x04,
	0x53, 0x69, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x78, 0x2e,
	0x50, 0x58, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6f,
	0x6f, 0x6b, 0x69, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x53, 0x43, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x52, 0x53, 0x43, 0x22, 0x4c, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x2a, 0x4f, 0x0a, 0x04, 0x53, 0x49, 0x54, 0x45, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41,
	0x4c, 0x4d, 0x41, 0x52, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x49, 0x42, 0x42, 0x45,
	0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x53, 0x45, 0x4e, 0x53, 0x45, 0x10, 0x02, 0x12,
	0x0a, 0x0a, 0x06, 0x53, 0x4e, 0x49, 0x50, 0x45, 0x53, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x4f,
	0x4e, 0x59, 0x47, 0x4f, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x4f, 0x4c, 0x45, 0x42, 0x4f,
	0x58, 0x10, 0x05, 0x2a, 0x81, 0x01, 0x0a, 0x06, 0x50, 0x58, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07,
	0x0a, 0x03, 0x50, 0x58, 0x33, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x58, 0x34, 0x10, 0x01,
	0x12, 0x09, 0x0a, 0x05, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x4d,
	0x4f, 0x45, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x4d, 0x45, 0x10, 0x04, 0x12, 0x06, 0x0a,
	0x02, 0x52, 0x45, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x41, 0x45, 0x10, 0x06, 0x12, 0x07,
	0x0a, 0x03, 0x42, 0x52, 0x45, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07, 0x48, 0x43, 0x41, 0x50, 0x4c,
	0x4f, 0x57, 0x10, 0x08, 0x12, 0x0c, 0x0a, 0x08, 0x48, 0x43, 0x41, 0x50, 0x48, 0x49, 0x47, 0x48,
	0x10, 0x09, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x43, 0x41, 0x50, 0x10, 0x0a, 0x12, 0x08, 0x0a,
	0x04, 0x50, 0x58, 0x33, 0x34, 0x10, 0x0b, 0x32, 0x9a, 0x01, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x69,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x58, 0x12, 0x4d, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x13, 0x2e, 0x70, 0x65, 0x72,
	0x69, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x78, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a,
	0x24, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x78, 0x2e, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x6b,
	0x69, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x78, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x78, 0x2e, 0x43, 0x6f,
	0x6f, 0x6b, 0x69, 0x65, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x74, 0x68, 0x65, 0x6e, 0x61,
	0x61, 0x2f, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x6f, 0x6e,
	0x69, 0x63, 0x2f, 0x61, 0x6e, 0x74, 0x69, 0x62, 0x6f, 0x74, 0x73, 0x2f, 0x70, 0x65, 0x72, 0x69,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PerimeterX_proto_rawDescOnce sync.Once
	file_PerimeterX_proto_rawDescData = file_PerimeterX_proto_rawDesc
)

func file_PerimeterX_proto_rawDescGZIP() []byte {
	file_PerimeterX_proto_rawDescOnce.Do(func() {
		file_PerimeterX_proto_rawDescData = protoimpl.X.CompressGZIP(file_PerimeterX_proto_rawDescData)
	})
	return file_PerimeterX_proto_rawDescData
}

var file_PerimeterX_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_PerimeterX_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_PerimeterX_proto_goTypes = []interface{}{
	(SITE)(0),                        // 0: perimeterx.SITE
	(PXType)(0),                      // 1: perimeterx.PXType
	(*GetCookieRequest)(nil),         // 2: perimeterx.GetCookieRequest
	(*Cookie)(nil),                   // 3: perimeterx.Cookie
	(*Payload)(nil),                  // 4: perimeterx.Payload
	(*ConstructPayloadResponse)(nil), // 5: perimeterx.ConstructPayloadResponse
}
var file_PerimeterX_proto_depIdxs = []int32{
	0, // 0: perimeterx.Payload.Site:type_name -> perimeterx.SITE
	1, // 1: perimeterx.Payload.Type:type_name -> perimeterx.PXType
	4, // 2: perimeterx.PerimeterX.ConstructPayload:input_type -> perimeterx.Payload
	2, // 3: perimeterx.PerimeterX.GetCookie:input_type -> perimeterx.GetCookieRequest
	5, // 4: perimeterx.PerimeterX.ConstructPayload:output_type -> perimeterx.ConstructPayloadResponse
	3, // 5: perimeterx.PerimeterX.GetCookie:output_type -> perimeterx.Cookie
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PerimeterX_proto_init() }
func file_PerimeterX_proto_init() {
	if File_PerimeterX_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PerimeterX_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCookieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PerimeterX_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cookie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PerimeterX_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PerimeterX_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConstructPayloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PerimeterX_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PerimeterX_proto_goTypes,
		DependencyIndexes: file_PerimeterX_proto_depIdxs,
		EnumInfos:         file_PerimeterX_proto_enumTypes,
		MessageInfos:      file_PerimeterX_proto_msgTypes,
	}.Build()
	File_PerimeterX_proto = out.File
	file_PerimeterX_proto_rawDesc = nil
	file_PerimeterX_proto_goTypes = nil
	file_PerimeterX_proto_depIdxs = nil
}
